### ISSUE TITLE
Can't upvote Synergies

### ISSUE THREAD

**Issue by jonathanhawleypeters** [jonathanhawleypeters/meta-ls#39]
POST http://localhost:8000/graphql 400 (Bad Request)
ApolloError.js:34 Uncaught (in promise) Error: GraphQL error: Variable "$token" of required type "String!" was not provided.
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:129
    at <anonymous>

**Comment by jesterswilde** [comment]
Fake news.
